### ISSUE TITLE
Rasterize eg

### ISSUE THREAD

**Issue by mark-williamson** [AndrSalvi/bigsss_violbattle#1]
https://stackoverflow.com/questions/32889531/r-how-can-i-count-how-many-points-are-in-each-cell-of-my-grid

**Comment by jessidraper** [comment]
`# load events data
acled_drc <- read.csv("acled_drc.csv")
drc.data <- as_tibble(acled_drc)

# filtering data
x <- filter(drc.data, EVENT_TYPE %in% c("Battle-Government regains territory",
                                    "Battle-Non-state actor overtakes territory",
                                    "Battle-No change of territory"))

y <- filter(drc.data, EVENT_TYPE %in% c("Violence against civilians"))

# convert battle events data to spatial dataframe
battle.pts <- cbind(x$LONGITUDE, x$LATITUDE) 
colnames(battle.pts) <- c("LONG","LAT") 
proj <- CRS("+proj=longlat +datum=WGS84") 
drc.battles <- SpatialPointsDataFrame(coords=battle.pts, data=x, proj4string=proj) 

# rasterize it for model
coordinates(x) <- ~LONGITUDE+LATITUDE
rast <- raster(ncol = 10, nrow = 10)
extent(rast) <- extent(x)
x.rast <- rasterize(drc.battles, rast, fun = function(x,...)length(x))
?rasterize
plot(x.rast)`

**Comment by kdonnay** [comment]
I am not sure if I fully understand the issue you are after but counting points within a cell/polygon is something that is really easy with the geomerge package.
